Added --verbose flag to kn repo

diff --git a/kn b/kn
--- a/kn
+++ b/kn
@@ -333,11 +333,17 @@ function repo {
 	__addarg "-h" "--help" "help" "optional" "" "Register a new repository with kn"
 	__addarg "-a" "--add" "storevalue" "optional" "" "The repository to register" "__verifydirectory"
 	__addarg "-p" "--pull" "flag" "optional" "" "Pull all registered repositories"
+	__addarg "-v" "--verbose" "flag" "optional" "" "When pulling, print standard Git output"
 	__addarg "-l" "--list" "flag" "optional" "" "List all registered repositories"
 	__addgroup "flags" "XOR" "optional" "--pull" "--list" "--add"
 	__parseargs "$@"
 
 	__verifykn
+
+	if [[ $pull -eq 0 && $verbose -eq 1 ]] ; then
+		__errortext "$koiname: err: the '--verbose' option is only valid when used with the '--pull' option"
+		return 1
+	fi
 
 	if [[ $list -eq 1 ]] ; then
 		local line repolist i output
@@ -368,12 +374,17 @@ function repo {
 		done < ~/.konphig/repos
 		for r in "${topull[@]}" ; do
 			name="$(basename "$r")"
-			echo -n "Pulling ${name}..."
-			(cd "$r" ; git pull > /dev/null 2>&1)
-			if [[ $? -ne 0 ]] ; then
-				echo "ERROR"
+			if [[ $verbose -eq 0 ]] ; then
+				echo -ne "Pulling \033[93m${name}\033[0m..."
+				(cd "$r" ; git pull > /dev/null 2>&1)
+				if [[ $? -ne 0 ]] ; then
+					echo -e "\033[91mERROR\033[0m"
+				else
+					echo -e "\033[92mDONE\033[0m"
+				fi
 			else
-				echo "DONE"
+				echo -e "Pulling \033[93m${name}\033[0m..."
+				(cd "$r" ; git pull)
 			fi
 		done
 		return
